// Authentication Constant
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
// category
export const SET_CATEGORY_LIST = "SET_CATEGORY_LIST";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_CATEGORY_NAME = "UPDATE_CATEGORY_NAME";
export const REORDER_QUESTIONS = "REORDER_QUESTIONS";
// QUESTIONs
export const ADD_QUESTION = "ADD_QUESTION";
export const UPATE_QUESTION = "UPATE_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";

//SUBCATEGORY
export const SET_SUBCATEGORY_LIST = "SET_SUBCATEGORY_LIST";
export const EDIT_SUBCATEGORY_NAME = "EDIT_SUBCATEGORY_NAME";
export const ADD_SUBCATEGORY_QUES = "ADD_SUBCATEGORY_QUES";
export const ADD_SUBCATEGORY_DOCU = "ADD_SUBCATEGORY_DOCU";
export const DELETE_SUBCATEGORY = "DELETE_SUBCATEGORY";
export const UPDATE_DOCUMENT = "UPDATE_DOCUMENT";
export const DELETE_DOCUMENT = "DELETE_DOCUMENT";
export const DELETE_QUESTION_SUBCATEGORY = "DELETE_QUESTION_SUBCATEGORY";
export const UPDATE_QUESTION_SUBCATEGORY = "UPDATE_QUESTION_SUBCATEGORY";
export const REORDER_SUBCATEGORY_QUESTIONS = "REORDER_SUBCATEGORY_QUESTIONS";
// CLIENT
export const SET_CATEGORY_WITH_SUBCATEGORY_AND_QUESTION =
  "SET_CATEGORY_WITH_SUBCATEGORY_AND_QUESTION";
export const SET_DRAFT_LIST = "SET_DRAFT_LIST";
export const DELETE_DRAFT_DATA = "DELETE_DRAFT_DATA";
export const SET_SUBCATEGORY = "SET_SUBCATEGORY";
export const ADD_CLIENT = "ADD_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";


// my file 
export const SET_MY_FILE_DETAILS = "SET_MY_FILE_DETAILS"
export const UPDATE_SINGLE_QUESTION_ANSWER = "UPDATE_SINGLE_QUESTION_ANSWER"
export const UPDATE_SINGLE_DOCUMENT_ANSWER = "UPDATE_SINGLE_DOCUMENT_ANSWER"

// Subscription
export const SET_CURRENT_SUBSCRIPTION = "SET_CURRENT_SUBSCRIPTION"
export const UPDATE_SUBSCRIPTION = "UPDATE_SUBSCRIPTION"

